#Steps Specific Configuration
general:
   changeManagement:
           endpoint: 'http://192.168.3.5:8000/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
           clientOpts: ''
           type: 'SOLMAN'

steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
   neo: 
    neoCredentialsId: 'NEO_DEPLOY'
    host: 'hana.ondemand.com'
    account: 'a3e36be73'
    transportRequestUploadFile:
      applicationId: 'HCP'
